name: isofit_env

channels: &id1
    - http://conda.anaconda.org/conda-forge

dependencies:
    - python>=3.7
    - pip
    - numpy>=1.20.0
    - protobuf~=3.19.0
    - scipy>=1.3.0
    - matplotlib>=2.2.2
    - scikit-learn>=0.19.1
    - scikit-image>=0.17.0
    - spectral>=0.19
    - pytest>=3.5.1
    - pep8>=1.7.1
    - pyyaml>=5.1.2
    - pandas>=0.24
    - gdal>=2.0.0
    - tensorflow>=2.0.1

    - pip:
      - isofit>=2.9.4
      - xxhash>=1.2.0
      - ray>=1.2.0
      - ndsplines>=0.1.2
      - sphinx-autodoc-typehints>=1.19.4
