name: isofit_env

channels: &id1
  - http://conda.anaconda.org/conda-forge

dependencies:
  - python>=3.8
  - pip
  - click
  - matplotlib>=2.2.2
  - numpy>=1.20.0
  - pandas>=0.24
  - pep8>=1.7.1
  - pre-commit
  - pygrib
  - pytest>=3.5.1
  - python-xxhash<3
  - pyyaml>=5.1.2
  - ray-default
  - scikit-image>=0.17.0
  - scikit-learn>=0.19.1
  - scipy>=1.3.0
  - spectral>=0.19
  - tensorflow >=2.0.1
  - utm

  - pip:
    - sphinx-autodoc-typehints>=1.19.4
