# Notes:
#   Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitely declared as shell: bash -el {0}
#   https://github.com/marketplace/actions/setup-miniconda#important
#
name: Examples

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    container:
      image: jammont/isofit:amd64
      options: --user root

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Enable ISOFIT Environment
      run: |
        echo PATH=/home/ray/anaconda3/envs/isofit/bin/:$PATH >> $GITHUB_ENV

    - name: Install Isofit
      run: |
<<<<<<< HEAD
        # conda env update --name isofit --solver=libmamba --file recipe/environment_isofit_basic.yml
        pip install xarray dask netCDF4
=======
>>>>>>> b4fd90c90bf6dd787646ca4229535b5523f496b9
        pip install --no-deps --force-reinstall --editable .

    - name: 20151026_SantaMonica
      run: |
        cd examples/20151026_SantaMonica
        bash run_examples.sh

    - name: 20171108_Pasadena
      run: |
        cd examples/20171108_Pasadena
        python run_example_modtran.py
        python run_topoflux_example.py

    # TODO: Temporarily disabled until examples are working locally
    # - name: 20190806_ThermalIR
    #   run: |
    #     cd examples/20190806_ThermalIR
    #     python run_example_modtran_one.py
    #
    # - name: profiling_cube/small
    #   run: |
    #     cd examples/profiling_cube
    #     ISOFIT_DEBUG=1 python run_profiling.py
