name: Hypertrace

on: [push, pull_request]

jobs:
  sRTMnet:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    container:
      image: jammont/isofit:amd64
      options: --user root

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Enable ISOFIT Environment
      run: |
        echo PATH=/home/ray/anaconda3/envs/isofit/bin/:$PATH >> $GITHUB_ENV

    - name: Install Isofit
      run: |
        pip install --no-deps .

    - name: Download and extract hypertrace data
      run: |
        cd examples/py-hypertrace
        wget https://github.com/ashiklom/isofit/releases/download/hypertrace-data/hypertrace-data.tar.gz
        tar -xf hypertrace-data.tar.gz

    - name: Run Hypertrace
      run: |
        cd examples/py-hypertrace
        # Modify the workflow file for GitHub actions
        python workflow.py configs/example-srtmnet-ci.json
        python summarize.py configs/example-srtmnet-ci.json

    - name: Upload summary from CI workflow
      uses: actions/upload-artifact@v2
      with:
        name: srtmnet-summary
        path: examples/py-hypertrace/output/example-srtmnet/summary.csv

#  libradtran:
#    runs-on: ubuntu-latest
#    container:
#      image: pgbrodrick/isofit
#
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#
#    - name: Install Isofit
#      run: |
#        pip3 install --editable .
#
#    - name: Download and install libradtran
#      run: |
#        cd examples/py-hypertrace
#        wget -nv http://www.libradtran.org/download/history/libRadtran-2.0.3.tar.gz
#        tar -xf libRadtran-2.0.3.tar.gz
#        cd libRadtran-2.0.3
#        wget -nv http://www.meteo.physik.uni-muenchen.de/~libradtran/lib/exe/fetch.php?media=download:reptran_2017_all.tar.gz -O reptran-2017-all.tar.gz
#        tar -xf reptran-2017-all.tar.gz
#        PYTHON=$(which python2) ./configure --prefix=$(pwd)
#        # For some reason, uvspecfunction compilation fails...
#        make --ignore-errors
#
#    - name: Download and extract Hypertrace data
#      run: |
#        cd examples/py-hypertrace
#        wget -nv https://github.com/ashiklom/isofit/releases/download/hypertrace-data/hypertrace-data.tar.gz
#        tar -xf hypertrace-data.tar.gz
#
#    - name: Run continuous integration workflow
#      run: |
#        cd examples/py-hypertrace
#        # Modify the workflow file for GitHub actions
#        export LIBRADTRAN_DIR=$GITHUB_WORKSPACE/libRadtran-2.0.3
#        python workflow.py configs/example-libradtran.json
#        python summarize.py configs/example-libradtran.json
#
#    - name: Upload summary from CI workflow
#      uses: actions/upload-artifact@v2
#      with:
#        name: summary-libradtran
#        path: examples/py-hypertrace/output-libradtran/summary.csv
