name: Main Tests

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: pgbrodrick/isofit

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Isofit
        pip3 install --editable .

    - name: Check Utils
      run: |
        python3 -c 'from isofit.utils import apply_oe'
        python3 -c 'from isofit.utils import empirical_line'
        python3 -c 'from isofit.utils import extractions'
        python3 -c 'from isofit.utils import instrument_model'
        python3 -c 'from isofit.utils import path'
        python3 -c 'from isofit.utils import remap'
        python3 -c 'from isofit.utils import segment'
        python3 -c 'from isofit.utils import surface_model'

    - name: Run Test
      run: |
        pytest
